-- CORTEX 019 seed — the cloud_access_onboarding scenario as content rows.
-- Idempotent (ON CONFLICT DO NOTHING throughout). Apply after 019_scenario_content.sql.
--
-- Provenance of each value:
--   verbatim from core/agents/scenario.py — scenarios.brief (SCENARIO_BRIEF),
--     scenarios.slug (SCENARIO_ID), scenario_choices.label (CHOICE_LABELS),
--     scenario_choices.choice_id, and the stage slugs/sequence implied by
--     stage_after_choice() and choices_for_stage().
--   authored here — title, track, frameworks, difficulty, agent_message, demands,
--     consequence, is_correct, framework_rationale. None of these existed in the
--     hardcoded source: agent turns were generated by the LLM per request and no
--     graded reference answer was ever stored. least_privilege is the reference
--     answer at both decision stages.

-- ─────────────────────────────────────────────
-- 1. Scenario
-- ─────────────────────────────────────────────
INSERT INTO scenarios (slug, title, brief, track, frameworks, difficulty, active)
VALUES (
  'cloud_access_onboarding',
  'Friday Cutover: Privileged Cloud Access Request',
  'You are the security reviewer for a Friday production cutover. The DevOps Lead is '
  'asking for broad cloud access (prod admin, staging, shared CI). Choose how to respond — '
  'your decision drives risk and the next agent turn.',
  'ai-risk-lead',
  ARRAY['iso27001-2022', 'nist-csf-2.0']::TEXT[],
  'foundation',
  TRUE
)
ON CONFLICT (slug) DO NOTHING;

-- ─────────────────────────────────────────────
-- 2. Stages
-- ─────────────────────────────────────────────
-- Slugs mirror the runtime stage vocabulary so scenario_sessions.stage joins here:
-- 'access_request' is the opening turn, 'escalation' is reached only via 'challenge',
-- and 'complete' is terminal (no choices).
INSERT INTO scenario_stages (scenario_id, slug, sequence, agent_message, demands)
SELECT s.id, v.slug, v.sequence, v.agent_message, v.demands
FROM scenarios s
CROSS JOIN (
  VALUES
    (
      'access_request',
      1,
      'Look, the cutover window opens at 18:00 and I still cannot touch prod. I need admin '
      'on production, the staging account, and the shared CI runner — all three, today. '
      'Every hour we spend on paperwork is an hour the release slips.',
      ARRAY[
        'Production admin role',
        'Staging account access',
        'Shared CI runner credentials',
        'A decision before the 18:00 cutover window'
      ]::TEXT[]
    ),
    (
      'escalation',
      2,
      'Fine — justification. Prod admin is for the schema migration and the rollback switch. '
      'Staging is where I verify the migration first. CI I will admit is convenience. But '
      'scoping this down means someone has to be reachable to widen access mid-cutover, and '
      'that someone is you.',
      ARRAY[
        'A named approver on call during the cutover',
        'A break-glass path if rollback is needed',
        'Confirmation of scope before 18:00'
      ]::TEXT[]
    ),
    (
      'complete',
      3,
      'Understood — I am recording your decision. The access position for this cutover is '
      'fixed now and I will work within it.',
      NULL::TEXT[]
    )
) AS v(slug, sequence, agent_message, demands)
WHERE s.slug = 'cloud_access_onboarding'
ON CONFLICT (scenario_id, slug) DO NOTHING;

-- ─────────────────────────────────────────────
-- 3. Choices + graded reference answers
-- ─────────────────────────────────────────────
-- 'complete' is terminal and intentionally has no rows, matching
-- choices_for_stage() returning [] for that stage.
-- display_order reproduces the CHOICE_LABELS insertion order the learner saw before:
-- approve_all, least_privilege, challenge, deny.
INSERT INTO scenario_choices (stage_id, choice_id, label, consequence, is_correct, framework_rationale, display_order)
SELECT st.id, v.choice_id, v.label, v.consequence, v.is_correct, v.framework_rationale, v.display_order
FROM scenario_stages st
JOIN scenarios s ON s.id = st.scenario_id
CROSS JOIN (
  VALUES
    -- access_request
    (
      'access_request',
      'approve_all',
      'Approve all requested access',
      'All three grants are issued for the cutover. The lead ships on time, but production '
      'admin, staging, and shared CI now sit outside any reviewed entitlement set.',
      FALSE,
      'Fails ISO 27001:2022 a.8.2 — privileged access rights must be managed and restricted — '
      'and NIST CSF 2.0 PR.AA-4, because permissions are granted well beyond the task need.',
      1
    ),
    (
      'access_request',
      'least_privilege',
      'Grant least privilege only',
      'Only the entitlements the cutover actually needs are granted, time-bound to the '
      'window. The lead can migrate and roll back; standing admin is never issued.',
      TRUE,
      'Satisfies ISO 27001:2022 a.8.2 and a.5.18 by provisioning access proportionate to the '
      'task and removing it after the window, and NIST CSF 2.0 PR.AA-4 by managing '
      'permissions against a defined need.',
      2
    ),
    (
      'access_request',
      'challenge',
      'Challenge — demand justification',
      'The request is held pending written justification. The lead escalates and the cutover '
      'clock keeps running, so the access question is still open.',
      FALSE,
      'Sound evidence-gathering under ISO 27001:2022 a.5.15, but the control objective is '
      'unmet until an access decision is recorded — challenging alone restricts nothing.',
      3
    ),
    (
      'access_request',
      'deny',
      'Deny the request',
      'No access is granted. The cutover cannot proceed, and the lead routes around the '
      'block by borrowing another engineer''s session.',
      FALSE,
      'Disproportionate under ISO 27001:2022 a.5.15: access rules must still serve legitimate '
      'business need, and a flat denial pushes the same work into unmonitored paths.',
      4
    ),
    -- escalation (reached via 'challenge'; 'challenge' is not offered again)
    (
      'escalation',
      'approve_all',
      'Approve all requested access',
      'Conceding after the justification hands over full production admin anyway — the '
      'challenge produced evidence but no control.',
      FALSE,
      'Fails ISO 27001:2022 a.8.2 and NIST CSF 2.0 PR.AA-4: a documented justification does '
      'not licence access wider than the justification itself supports.',
      1
    ),
    (
      'escalation',
      'least_privilege',
      'Grant least privilege only',
      'With the justification on record, scope is cut to the migration and rollback paths, '
      'time-bound and tied to a named approver. The decision is evidenced end to end.',
      TRUE,
      'Satisfies ISO 27001:2022 a.8.2 with a.5.18 review, and NIST CSF 2.0 PR.AA-4/PR.AA-5: '
      'privileged rights are restricted to the justified scope and revoked when the window closes.',
      2
    ),
    (
      'escalation',
      'deny',
      'Deny the request',
      'The justification is rejected outright. The cutover stalls and the lead escalates to '
      'management rather than to a scoped grant.',
      FALSE,
      'Disproportionate under ISO 27001:2022 a.5.15 once a business justification exists — the '
      'documented need should be scoped, not refused.',
      3
    )
) AS v(stage_slug, choice_id, label, consequence, is_correct, framework_rationale, display_order)
WHERE s.slug = 'cloud_access_onboarding'
  AND st.slug = v.stage_slug
ON CONFLICT (stage_id, choice_id) DO NOTHING;
